DROP TABLE IF EXISTS transaction_statuses;

CREATE TABLE transaction_statuses (
  id SERIAL PRIMARY KEY,  
  name VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

