apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-service
  template:
    metadata:
      labels:
        app: authentication-service
    spec:
      containers:
      - name: authentication-service
        image: auth-service:latest # Replace with actual image name or use build automation
        ports:
          - containerPort: 80
        env:
          - name: REDIS_URL
            value: "redis://redis:6379"
          - name: VAULT_ADDR
            value: "http://vault:8200"
          - name: VAULT_TOKEN
            value: root_token
