apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --chart
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: admin-service
  name: admin-service
spec:
  ports:
    - name: "8082"
      port: 8082
      targetPort: 80
    - name: "50002"
      port: 50002
      targetPort: 50001
  selector:
    io.kompose.service: admin-service
