apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service
  labels:
    app: admin-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
    spec:
      containers:
        - name: admin-service
          image: your-registry/admin-service:latest
          ports:
            - containerPort: 80
          env:
            - name: DSN
              value: "host=postgres-admins port=5432 user=postgres password=password dbname=admins sslmode=disable timezone=UTC connect_timeout=5"
            - name: VAULT_ADDR
              value: "http://vault:8200"
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault-secret
                  key: VAULT_DEV_ROOT_TOKEN_ID
      restartPolicy: Always
