apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
        - name: vault
          image: 'vault:1.13.2'
          ports:
            - containerPort: 8200
          envFrom:
            - configMapRef:
                name: vault-config
            - secretRef:
                name: vault-secrets
          volumeMounts:
            - mountPath: /vault/file
              name: vault-data
          securityContext:
            capabilities:
              add: ["IPC_LOCK"]
      volumes:
        - name: vault-data
          persistentVolumeClaim:
            claimName: vault-data
