apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  labels:
    app: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
        - name: vault
          image: vault:1.13.2
          ports:
            - containerPort: 8200
          env:
            - name: VAULT_ADDR
              value: "http://0.0.0.0:8200"
            - name: VAULT_API_ADDR
              value: "http://localhost:8200"
            - name: VAULT_DEV_ROOT_TOKEN_ID
              value: "root_token"
          securityContext:
            capabilities:
              add: ["IPC_LOCK"]
          volumeMounts:
            - name: vault-data
              mountPath: /vault/file
      volumes:
        - name: vault-data
          persistentVolumeClaim:
            claimName: vault-pvc
