apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-service
  template:
    metadata:
      labels:
        app: authentication-service
    spec:
      containers:
        - name: authentication-service
          image: your_auth_service_image  # Zmień na odpowiedni obraz
          ports:
            - containerPort: 80
          env:
            - name: REDIS_URL
              value: "redis://redis:6379"
            - name: VAULT_ADDR
              value: "http://vault:8200"
            - name: VAULT_TOKEN
              value: "root_token"
---
apiVersion: v1
kind: Service
metadata:
  name: authentication-service
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: authentication-service
