# k8s/vault.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
        - name: vault
          image: vault:1.13.2
          ports:
            - containerPort: 8200
          env:
            - name: VAULT_ADDR
              value: "http://0.0.0.0:8200"
            - name: VAULT_API_ADDR
              value: "http://localhost:8200"
            - name: VAULT_DEV_ROOT_TOKEN_ID
              value: "root_token"
          volumeMounts:
            - name: vault-data
              mountPath: /vault/file
          command: ["server", "-dev", "-dev-root-token-id=root_token"]
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
      volumes:
        - name: vault-data
          emptyDir: {}  # Możesz użyć PersistentVolumeClaim dla dłuższego przechowywania danych
---
apiVersion: v1
kind: Service
metadata:
  name: vault
spec:
  ports:
    - port: 8200
      targetPort: 8200
  selector:
    app: vault
