apiVersion: v1
kind: ConfigMap
metadata:
  name: mailer-service-config
data:
  MAIL_DOMAIN: "localhost"
  MAIL_HOST: "mailhog"
  MAIL_PORT: "1025"
  MAIL_ENCRYPTION: "none"
  MAIL_USERNAME: ""
  MAIL_PASSWORD: ""
  FROM_NAME: "Karol"
  FROM_ADDRESS: "goappdm@gmail.com"
