apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: authentication-service
  name: authentication-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: authentication-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: authentication-service
    spec:
      containers:
        - env:
            - name: REDIS_URL
              value: redis:6379
            - name: VAULT_ADDR
              value: http://vault:8200
            - name: VAULT_TOKEN
              value: root_token
          image: authentication-service
          name: authentication-service
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
