pipeline {
    agent any
    environment {
        DOCKER_REGISTRY = "975050173579.dkr.ecr.eu-central-1.amazonaws.com"
        AWS_REGION = "eu-central-1"
        KUBECTL_PATH = "/usr/local/bin/kubectl"
        HELM_PATH = "/usr/local/bin/helm"  
        KUBECONFIG = '/var/lib/jenkins/minikube/kubeconfig'
    }
    stages {
        stage('Login to ECR') {
            steps {
                script {
                    sh """
                        aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${DOCKER_REGISTRY}
                    """
                }
            }
        }

        stage('Build Applications') {
            steps {
                script {
                    def binaries = [
                        'auth-service': 'authApp',
                        'user-service': 'userApp',
                        'admin-service': 'adminApp',
                        'mail-service': 'mailApp',
                        'logger-service': 'loggerApp'
                    ]
                    
                    binaries.each { service, binaryName ->
                        dir("./${service}") {
                            sh """
                                echo "Building ${service} binary..."
                                env GOOS=linux CGO_ENABLED=0 go build -o ${binaryName} ./cmd/api
                                echo "Built ${service} binary!"
                            """
                        }
                    }
                }
            }
        }

        stage('Build Docker Images') {
            steps {
                script {
                    def services = ['auth-service', 'user-service', 'admin-service', 'mail-service', 'logger-service']
                    
                    services.each { service ->
                        dir("./${service}") {
                            sh "docker build -t ${DOCKER_REGISTRY}/${service}:latest -f ${service}.dockerfile ."
                        }
                    }
                }
            }
        }

        stage('Tag and Push Docker Images') {
            steps {
                script {
                    def services = ['auth-service', 'user-service', 'admin-service', 'mail-service', 'logger-service']
                    
                    services.each { service ->
                        sh "docker tag ${DOCKER_REGISTRY}/${service}:latest ${DOCKER_REGISTRY}/${service}:latest"
                        sh "docker push ${DOCKER_REGISTRY}/${service}:latest"
                    }
                }
            }
        }
        
        stage('Deploy with Helm') {
            steps {
                script {
                    sh "${HELM_PATH} upgrade --install microservices ./my-helm-chart --namespace microservices-app --set image.tag=latest --debug"
                }
            }
        }
    }
}
