{{- $vault := .Values.vault -}}
{{- range $service, $image := .Values.image }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $service | lower }}
  labels:
    app: {{ $service | lower }}
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ $service | lower }}
  template:
    metadata:
      labels:
        app: {{ $service | lower }}
    spec:
      containers:
        - name: {{ $service | lower }}
          image: {{ $image }}
          ports:
            - containerPort: 80
          env:
            - name: VAULT_ADDR
              value: {{ $vault.address }}
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault-secret
                  key: VAULT_DEV_ROOT_TOKEN_ID
            {{- if eq $service "authService" }}
            - name: REDIS_URL
              value: "redis:6379"
            {{- end }}
            {{- if eq $service "userService" }}
            - name: DSN
              value: "host=postgres-users port=5432 user={{ $.Values.database.postgres.username }} password={{ $.Values.database.postgres.password }} dbname={{ $.Values.database.postgres.usersDb }} sslmode=disable"
            {{- end }}
          volumeMounts:
            - mountPath: "/vault/file"
              name: vault-data
{{- end }}
