gcp_credentials_file = "/home/karol/terraform/cred/my-microservices-app-c0b0ae362292.json"
gcp_project          = "my-microservices-app"
gcp_region           = "us-central1"
gcp_zone             = "us-central1-a"
kms_keyring          = "vault-keyring"
kms_key              = "vault-init-key"
