apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml -o new-chart/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: vault
  name: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: vault
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml -o new-chart/
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: vault
    spec:
      containers:
        - args:
            - server
            - -dev
            - -dev-root-token-id=root_token
          env:
            - name: VAULT_ADDR
              value: http://0.0.0.0:8200
            - name: VAULT_API_ADDR
              value: http://localhost:8200
            - name: VAULT_DEV_ROOT_TOKEN_ID
              value: root_token
          image: vault:1.13.2
          name: vault
          ports:
            - containerPort: 8200
              protocol: TCP
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          volumeMounts:
            - mountPath: /vault/file
              name: vault-claim0
      restartPolicy: Always
      volumes:
        - name: vault-claim0
          persistentVolumeClaim:
            claimName: vault-claim0
