global:
  imagePullSecrets:
    - name: gcr-json-key

  # Wspólne zmienne środowiskowe
  vaultAddr: "http://microservices-vault-service.microservices-app.svc.cluster.local:8200"
  vaultToken: "root_token"

vault:
  image:
    repository: "hashicorp/vault"
    tag: "1.10.0"  # Konkretna wersja zamiast 'latest'
  environment:
    VAULT_DEV_ROOT_TOKEN_ID: "{{ .Values.global.vaultToken }}"
    VAULT_ADDR: "{{ .Values.global.vaultAddr }}"
  volumes:
    data:
      size: 1Gi
  ports:
    - name: http
      containerPort: 8200

authenticationService:
  image:
    repository: "us-central1-docker.pkg.dev/my-microservices-app/my-microservices-repo/auth-service"
    tag: "1.0.0"
  environment:
    VAULT_ADDR: "{{ .Values.global.vaultAddr }}"
    VAULT_TOKEN: "{{ .Values.global.vaultToken }}"
    REDIS_URL: "microservices-redis-service.microservices-app.svc.cluster.local:6379"
  ports:
    - name: http
      containerPort: 8083

loggerService:
  image:
    repository: "us-central1-docker.pkg.dev/my-microservices-app/my-microservices-repo/logger-service"
    tag: "1.0.0"

mailerService:
  image:
    repository: "us-central1-docker.pkg.dev/my-microservices-app/my-microservices-repo/mail-service"
    tag: "1.0.0"
  environment:
    MAIL_HOST: "mailhog"
    MAIL_PORT: "1025"
    FROM_NAME: "Karol"
    FROM_ADDRESS: "goappdm@gmail.com"
  ports:
    - name: http
      containerPort: 8085

userService:
  image:
    repository: "us-central1-docker.pkg.dev/my-microservices-app/my-microservices-repo/user-service"
    tag: "1.0.0"
  environment:
    DSN: "host=postgres-users-service.microservices-app port=5432 user=postgres password=password dbname=users sslmode=disable"
    VAULT_ADDR: "{{ .Values.global.vaultAddr }}"
    VAULT_TOKEN: "{{ .Values.global.vaultToken }}"
  ports:
    - name: http
      containerPort: 8081
    - name: grpc
      containerPort: 50001

adminService:
  image:
    repository: "us-central1-docker.pkg.dev/my-microservices-app/my-microservices-repo/admin-service"
    tag: "1.0.0"
  environment:
    DSN: "host=postgres-users-service.microservices-app port=5432 user=postgres password=password dbname=users sslmode=disable"
    VAULT_ADDR: "{{ .Values.global.vaultAddr }}"
    VAULT_TOKEN: "{{ .Values.global.vaultToken }}"
  ports:
    - name: http
      containerPort: 8082
    - name: grpc
      containerPort: 50002

redis:
  image:
    repository: "redis"
    tag: "7.0"  # Określenie konkretnej wersji obrazu
  ports:
    - containerPort: 6379

postgresUsers:
  image:
    repository: "postgres"
    tag: "14.0"
  environment:
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "password"
    POSTGRES_DB: "users"
  volumes:
    data:
      size: 1Gi

postgresAdmins:
  image:
    repository: "postgres"
    tag: "14.0"
  environment:
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "password"
    POSTGRES_DB: "admins"
  volumes:
    data:
      size: 1Gi

mongo:
  image:
    repository: "mongo"
    tag: "4.2.16-bionic"
  environment:
    MONGO_INITDB_DATABASE: "logs"
    MONGO_INITDB_ROOT_USERNAME: "admin"
    MONGO_INITDB_ROOT_PASSWORD: "password"
  volumes:
    data:
      size: 1Gi
