apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml --chart
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: admin-service
  name: admin-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: admin-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml --chart
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: admin-service
    spec:
      containers:
        - env:
            - name: DSN
              value: host=postgres-admins port=5432 user=postgres password=password dbname=users sslmode=disable timezone=UTC connect_timeout=5
            - name: VAULT_ADDR
              value: http://vault:8200
            - name: VAULT_TOKEN
              value: root_token
          image: admin-service
          name: admin-service
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 50001
              protocol: TCP
      restartPolicy: Always
