apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: injector-certificate
  namespace: microservices-app
spec:
  secretName: injector-tls
  duration: 24h
  renewBefore: 144m  
  dnsNames:
    - vault.microservices-app.svc.cluster.local
  issuerRef:
    name: injector-ca-issuer
  commonName: Agent Inject Cert
