apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-agent-config
  namespace: microservices-app
data:
  config.hcl: |
    "listener" = {
      "tcp" = {
        "address" = "0.0.0.0:8200"
        "tls_disable" = false
        "tls_cert_file" = "/vault/tls/vault.crt"
        "tls_key_file" = "/vault/tls/vault.key"
      }
    }

    "storage" = {
      "raft" = {
        "path" = "/vault/data"
      }
    }

    "default_lease_ttl" = "1h"
    "max_lease_ttl" = "72h"

    "ui" = true
