apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  labels:
    app: vault
    release: {{ .Release.Name }}
data:
  vault.hcl: |
    # Listener configuration for Vault API and cluster communication
    listener "tcp" {
      address       = "0.0.0.0:8200"  # Vault API listener (accessed externally)
      cluster_address = "0.0.0.0:8201" # Vault cluster communication listener (for HA)
      tls_disable   = true  # Disable TLS for simplicity (set to 'false' in production)
    }

    # Storage backend configuration (Using Consul in this case)
    storage "consul" {
      address = "microservices-consul-service.microservices-app.svc.cluster.local:8500"
      path    = "vault/"
      scheme  = "http"
    }

    # Enable Vault UI
    ui = true

    # Enable transit backend for key management
    secrets "transit" {}

    # Kubernetes Auth configuration
    auth "kubernetes" {
      kubelet_address = "https://kubernetes.default.svc"
      token_reviewer_jwt = "/var/run/secrets/kubernetes.io/serviceaccount/token"
      kubernetes_host = "https://kubernetes.default.svc"
    }

    # Seal configuration using Google Cloud KMS
    seal "gcpckms" {
      project     = "your-gcp-project-id"
      region      = "your-gcp-region"
      key_ring    = "your-key-ring"
      crypto_key  = "your-crypto-key"
      credentials = "/path/to/your/service-account-file.json"
      auto_unseal = true  # Automatyczne unseal
    }
