apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  labels:
    app: vault
    release: {{ .Release.Name }}
data:
  vault.hcl: |
    listener "tcp" {
      address = "0.0.0.0:8200"
      cluster_address = "0.0.0.0:8201"
      tls_disable = true
    }

    storage "consul" {
      address = "{{ .Values.vault.ha.backend.consul.address }}"
      path = "{{ .Values.vault.ha.backend.consul.path }}"
      scheme = "{{ .Values.vault.ha.backend.consul.scheme }}"
    }

    api_addr = "http://{{ .Release.Name }}-vault-service:8200"
    cluster_addr = "http://{{ .Release.Name }}-vault:8201"
    ui = true
