apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-vault
  labels:
    app: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      imagePullSecrets:
        - name: gcr-json-key  # Dodajemy secret do pobierania obrazów z Artifact Registry
      containers:
        - name: vault
          image: "{{ .Values.vault.image.repository }}:{{ .Values.vault.image.tag }}"
          ports:
            - containerPort: 8200
          env:
            - name: VAULT_ADDR
              value: "{{ .Values.vault.environment.VAULT_ADDR }}"
            - name: VAULT_API_ADDR
              value: "{{ .Values.vault.environment.VAULT_API_ADDR }}"
            - name: VAULT_DEV_ROOT_TOKEN_ID
              value: "{{ .Values.vault.environment.VAULT_DEV_ROOT_TOKEN_ID }}"
          volumeMounts:
            - name: vault-data
              mountPath: /vault/file
          command: ["server", "-dev", "-dev-root-token-id=root_token"]
          securityContext:
            capabilities:
              add: ["IPC_LOCK"]
      volumes:
        - name: vault-data
          emptyDir: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-authentication-service
  labels:
    app: authentication-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-service
  template:
    metadata:
      labels:
        app: authentication-service
    spec:
      imagePullSecrets:
        - name: gcr-json-key  # Dodajemy secret do pobierania obrazów z Artifact Registry
      containers:
        - name: authentication-service
          image: "{{ .Values.authenticationService.image.buildContext }}/{{ .Values.authenticationService.image.dockerfile }}"
          ports:
            - containerPort: 8083
          env:
            - name: REDIS_URL
              value: "{{ .Values.authenticationService.environment.REDIS_URL }}"
            - name: VAULT_ADDR
              value: "{{ .Values.authenticationService.environment.VAULT_ADDR }}"
            - name: VAULT_TOKEN
              value: "{{ .Values.authenticationService.environment.VAULT_TOKEN }}"
          dependsOn:
            - vault
            - redis

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-logger-service
  labels:
    app: logger-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logger-service
  template:
    metadata:
      labels:
        app: logger-service
    spec:
      imagePullSecrets:
        - name: gcr-json-key  # Dodajemy secret do pobierania obrazów z Artifact Registry
      containers:
        - name: logger-service
          image: "{{ .Values.loggerService.image.buildContext }}/{{ .Values.loggerService.image.dockerfile }}"
          ports:
            - containerPort: 8084

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mailer-service
  labels:
    app: mailer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailer-service
  template:
    metadata:
      labels:
        app: mailer-service
    spec:
      imagePullSecrets:
        - name: gcr-json-key  # Dodajemy secret do pobierania obrazów z Artifact Registry
      containers:
        - name: mailer-service
          image: "{{ .Values.mailerService.image.buildContext }}/{{ .Values.mailerService.image.dockerfile }}"
          ports:
            - containerPort: 8085
          env:
            - name: MAIL_DOMAIN
              value: "{{ .Values.mailerService.environment.MAIL_DOMAIN }}"
            - name: MAIL_HOST
              value: "{{ .Values.mailerService.environment.MAIL_HOST }}"
            - name: MAIL_PORT
              value: "{{ .Values.mailerService.environment.MAIL_PORT }}"
            - name: MAIL_ENCRYPTION
              value: "{{ .Values.mailerService.environment.MAIL_ENCRYPTION }}"
            - name: MAIL_USERNAME
              value: "{{ .Values.mailerService.environment.MAIL_USERNAME }}"
            - name: MAIL_PASSWORD
              value: "{{ .Values.mailerService.environment.MAIL_PASSWORD }}"
            - name: FROM_NAME
              value: "{{ .Values.mailerService.environment.FROM_NAME }}"
            - name: FROM_ADDRESS
              value: "{{ .Values.mailerService.environment.FROM_ADDRESS }}"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-user-service
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      imagePullSecrets:
        - name: gcr-json-key  # Dodajemy secret do pobierania obrazów z Artifact Registry
      containers:
        - name: user-service
          image: "{{ .Values.userService.image.buildContext }}/{{ .Values.userService.image.dockerfile }}"
          ports:
            - containerPort: 8081
            - containerPort: 50001
          env:
            - name: DSN
              value: "{{ .Values.userService.environment.DSN }}"
            - name: VAULT_ADDR
              value: "{{ .Values.userService.environment.VAULT_ADDR }}"
            - name: VAULT_TOKEN
              value: "{{ .Values.userService.environment.VAULT_TOKEN }}"
          dependsOn:
            - postgres-users
            - vault

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-admin-service
  labels:
    app: admin-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
    spec:
      imagePullSecrets:
        - name: gcr-json-key  # Dodajemy secret do pobierania obrazów z Artifact Registry
      containers:
        - name: admin-service
          image: "{{ .Values.adminService.image.buildContext }}/{{ .Values.adminService.image.dockerfile }}"
          ports:
            - containerPort: 8082
            - containerPort: 50002
          env:
            - name: DSN
              value: "{{ .Values.adminService.environment.DSN }}"
            - name: VAULT_ADDR
              value: "{{ .Values.adminService.environment.VAULT_ADDR }}"
            - name: VAULT_TOKEN
              value: "{{ .Values.adminService.environment.VAULT_TOKEN }}"
          dependsOn:
            - postgres-admins
            - vault

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      imagePullSecrets:
        - name: gcr-json-key  # Dodajemy secret do pobierania obrazów z Artifact Registry
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          ports:
            - containerPort: 6379

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgres-users
  labels:
    app: postgres-users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-users
  template:
    metadata:
      labels:
        app: postgres-users
    spec:
      imagePullSecrets:
        - name: gcr-json-key  # Dodajemy secret do pobierania obrazów z Artifact Registry
      containers:
        - name: postgres-users
          image: "{{ .Values.postgresUsers.image.repository }}:{{ .Values.postgresUsers.image.tag }}"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "{{ .Values.postgresUsers.environment.POSTGRES_USER }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.postgresUsers.environment.POSTGRES_PASSWORD }}"
            - name: POSTGRES_DB
              value: "{{ .Values.postgresUsers.environment.POSTGRES_DB }}"
          volumeMounts:
            - name: postgres-users-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-users-data
          hostPath:
            path: ./db-data/postgres-users

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgres-admins
  labels:
    app: postgres-admins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-admins
  template:
    metadata:
      labels:
        app: postgres-admins
    spec:
      imagePullSecrets:
        - name: gcr-json-key  # Dodajemy secret do pobierania obrazów z Artifact Registry
      containers:
        - name: postgres-admins
          image: "{{ .Values.postgresAdmins.image.repository }}:{{ .Values.postgresAdmins.image.tag }}"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "{{ .Values.postgresAdmins.environment.POSTGRES_USER }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.postgresAdmins.environment.POSTGRES_PASSWORD }}"
            - name: POSTGRES_DB
              value: "{{ .Values.postgresAdmins.environment.POSTGRES_DB }}"
          volumeMounts:
            - name: postgres-admins-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-admins-data
          hostPath:
            path: ./db-data/postgres-admins

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mongo
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      imagePullSecrets:
        - name: gcr-json-key  # Dodajemy secret do pobierania obrazów z Artifact Registry
      containers:
        - name: mongo
          image: "{{ .Values.mongo.image.repository }}:{{ .Values.mongo.image.tag }}"
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_DATABASE
              value: "{{ .Values.mongo.environment.MONGO_INITDB_DATABASE }}"
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "{{ .Values.mongo.environment.MONGO_INITDB_ROOT_USERNAME }}"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "{{ .Values.mongo.environment.MONGO_INITDB_ROOT_PASSWORD }}"
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          hostPath:
            path: ./db-data/mongo
