apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-rolebinding
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: vault-service-account
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: vault-role
  apiGroup: rbac.authorization.k8s.io
