apiVersion: v1
kind: Service
metadata:
  name: vault-service
  labels:
    app: vault
spec:
  selector:
    app: vault
  ports:
    - protocol: TCP
      port: 8200
      targetPort: 8200
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: authentication-service
  labels:
    app: authentication-service
spec:
  selector:
    app: authentication-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8083
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: logger-service
  labels:
    app: logger-service
spec:
  selector:
    app: logger-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8084
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: mailer-service
  labels:
    app: mailer-service
spec:
  selector:
    app: mailer-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8085
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  selector:
    app: user-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8081
    - name: api
      protocol: TCP
      port: 50001
      targetPort: 50001
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: admin-service
  labels:
    app: admin-service
spec:
  selector:
    app: admin-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8082
    - name: api
      protocol: TCP
      port: 50002
      targetPort: 50001
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-users-service
  labels:
    app: postgres-users
spec:
  selector:
    app: postgres-users
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-admins-service
  labels:
    app: postgres-admins
spec:
  selector:
    app: postgres-admins
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    app: mongo
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
