---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-logger-service
  labels:
    app: logger-service
    release: {{ .Release.Name }}
spec:
  selector:kind: Service
metadata:
  name: {{ .Release.Name }}-logger-service
  labels:
    app: logger-service
    release: {{ .Release.Name }}
spec:
  selector:
    app: logger-service
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8084
  type: ClusterIP
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8084
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-vault-service
  labels:
    app: vault
    release: {{ .Release.Name }}
spec:
  selector:
    app: vault
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 8200
      targetPort: 8200


---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis-service
  labels:
    app: redis
    release: {{ .Release.Name }}
spec:
  selector:
    app: redis
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres-users-service
  labels:
    app: postgres-users
    release: {{ .Release.Name }}
spec:
  selector:
    app: postgres-users
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres-admins-service
  labels:
    app: postgres-admins
    release: {{ .Release.Name }}
spec:
  selector:
    app: postgres-admins
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongo-service
  labels:
    app: mongo
    release: {{ .Release.Name }}
spec:
  selector:
    app: mongo
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-authentication-service
  labels:
    app: authentication-service
    release: {{ .Release.Name }}
spec:
  selector:
    app: authentication-service
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP


---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-user-service
  labels:
    app: user-service
    release: {{ .Release.Name }}
spec:
  selector:
    app: user-service
    release: {{ .Release.Name }}
  ports:
    - name: http  # Dodano nazwę
      protocol: TCP
      port: 8081
      targetPort: 8081
    - name: grpc  # Dodano nazwę
      protocol: TCP
      port: 50001
      targetPort: 50001
  type: ClusterIP



---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-admin-service
  labels:
    app: admin-service
    release: {{ .Release.Name }}
spec:
  selector:
    app: admin-service
    release: {{ .Release.Name }}
  ports:
    - name: http  # Dodano nazwę
      protocol: TCP
      port: 8082
      targetPort: 8082
    - name: grpc  # Dodano nazwę
      protocol: TCP
      port: 50002
      targetPort: 50002
  type: ClusterIP
