apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-vault
  labels:
    app: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    spec:
      containers:
        - name: vault
          image: "{{ .Values.vault.image.repository }}:{{ .Values.vault.image.tag }}"
          command: ["sh", "-c", |
            # Inicjalizacja metod autoryzacji Kubernetes w Vault
            vault auth enable kubernetes

            # Tworzymy rolę w Vault dla naszej aplikacji
            vault write auth/kubernetes/role/my-app \
              bound_service_account_names=my-app-serviceaccount \
              bound_service_account_namespaces=default \
              policies=jwt_policy \
              ttl=24h

            # Włączamy KV secrets engine i zapisujemy sekrety
            vault secrets enable -path=jwt_keys kv
            vault kv put jwt_keys/public_keys public_key=@public_key.pem
            vault kv put jwt_keys/private_key private_key=@private_key.pem
            exit
          ]
          env:
            - name: VAULT_ADDR
              value: "http://microservices-vault-service.microservices-app.svc.cluster.local:8200"
            - name: VAULT_DEV_ROOT_TOKEN_ID
              value: "root_token"
